services:
    wizhippo.paginated_query_controller:
        class: Wizhippo\Bundle\EzCoreExtraBundle\Controller\PagerFantaQueryController
        arguments:
            - '@ezpublish.query_type_content_view_mapper'
            - '@ezpublish.api.service.search'
